export const FALLBACK_OCCUPANCY_ROWS = [
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100A",
    "putawayzone": "R1100A",
    "descr": "LIVING UPHOLSTERED",
    "cbmLoc": 5886,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100I",
    "putawayzone": "R1100I",
    "descr": "LIGHTING",
    "cbmLoc": 170,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100J",
    "putawayzone": "R1100J",
    "descr": "MATTRESS",
    "cbmLoc": 24,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100M",
    "putawayzone": "R1100M",
    "descr": "HOME TEXTILE",
    "cbmLoc": 643,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100N",
    "putawayzone": "R1100N",
    "descr": "HOME DECORE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100O",
    "putawayzone": "R1100O",
    "descr": "HOMEWARE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100X",
    "putawayzone": "R1100X",
    "descr": "NON MERCHANDISE",
    "cbmLoc": 3,
    "stock": 3,
    "utilization": 85.9
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AB",
    "putawayzone": "R110AB",
    "descr": "HOME CLASSIC",
    "cbmLoc": 4884,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AE",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AF",
    "putawayzone": "R110AF",
    "descr": "BROWN GOODS",
    "cbmLoc": 111,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AG",
    "putawayzone": "R110AG",
    "descr": "WHITE GOODS",
    "cbmLoc": 455,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AM",
    "putawayzone": "R110AM",
    "descr": "CUSTOME FURNITURE",
    "cbmLoc": 2,
    "stock": 1,
    "utilization": 47.5
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AQ",
    "putawayzone": "R110AQ",
    "descr": "SELMA",
    "cbmLoc": 126,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 6973,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BB",
    "putawayzone": "R110BB",
    "descr": "TABLE & CABINET",
    "cbmLoc": 10059,
    "stock": 1109,
    "utilization": 11
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BC",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 5014,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BD",
    "putawayzone": "R110BD",
    "descr": "DINING",
    "cbmLoc": 2737,
    "stock": 1856,
    "utilization": 67.8
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BE",
    "putawayzone": "R110BE",
    "descr": "KITCHEN",
    "cbmLoc": 247,
    "stock": 246,
    "utilization": 99.8
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BF",
    "putawayzone": "R110BF",
    "descr": "BEDROOM",
    "cbmLoc": 2775,
    "stock": 1858,
    "utilization": 67
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BG",
    "putawayzone": "R110BG",
    "descr": "MATTRESS",
    "cbmLoc": 9138,
    "stock": 5759,
    "utilization": 63
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BH",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 119,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BI",
    "putawayzone": "R110BI",
    "descr": "KIDS SPACE",
    "cbmLoc": 996,
    "stock": 644,
    "utilization": 64.6
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BJ",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 368,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BK",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 977,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BL",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 61,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BM",
    "putawayzone": "R110BM",
    "descr": "HOME ORGANIZER",
    "cbmLoc": 541,
    "stock": 499,
    "utilization": 92.3
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BN",
    "putawayzone": "R110BN",
    "descr": "HOMEWARE",
    "cbmLoc": 364,
    "stock": 124,
    "utilization": 34
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BO",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 10,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BP",
    "putawayzone": "R110BP",
    "descr": "OFFICE",
    "cbmLoc": 2839,
    "stock": 1468,
    "utilization": 51.7
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BQ",
    "putawayzone": "R110BQ",
    "descr": "OFFICE SEATING",
    "cbmLoc": 4276,
    "stock": 4853,
    "utilization": 113.5
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BR",
    "putawayzone": "R110BR",
    "descr": "COMMERCIAL & BUSINESS",
    "cbmLoc": 6248,
    "stock": 4106,
    "utilization": 65.7
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 435,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CB",
    "putawayzone": "R110CB",
    "descr": "TEXTILE",
    "cbmLoc": 428,
    "stock": 3,
    "utilization": 0.6
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CC",
    "putawayzone": "R110CC",
    "descr": "KASUR",
    "cbmLoc": 955,
    "stock": 253,
    "utilization": 26.4
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CD",
    "putawayzone": "R110CD",
    "descr": "RUANG TAMU & PENYIMPANAN",
    "cbmLoc": 449,
    "stock": 115,
    "utilization": 25.6
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CE",
    "putawayzone": "R110CE",
    "descr": "RUANG MAKAN & DAPUR",
    "cbmLoc": 731,
    "stock": 104,
    "utilization": 14.2
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CF",
    "putawayzone": "R110CF",
    "descr": "PERALATAN MAKAN & DAPUR",
    "cbmLoc": 126,
    "stock": 15,
    "utilization": 11.9
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CG",
    "putawayzone": "R110CG",
    "descr": "RUANG TIDUR",
    "cbmLoc": 428,
    "stock": 92,
    "utilization": 21.4
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CH",
    "putawayzone": "R110CH",
    "descr": "PERLENGKAPAN RUMAH",
    "cbmLoc": 428,
    "stock": 17,
    "utilization": 3.9
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CI",
    "putawayzone": "R110CI",
    "descr": "RUANG KERJA & BELAJAR",
    "cbmLoc": 1645,
    "stock": 132,
    "utilization": 8
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DA",
    "putawayzone": "R110DA",
    "descr": "KELS - MAJOR DOMESTIC APPLIANCES",
    "cbmLoc": 209,
    "stock": 26,
    "utilization": 12.6
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DB",
    "putawayzone": "R110DB",
    "descr": "KELS - SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 212,
    "stock": 27,
    "utilization": 12.9
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DC",
    "putawayzone": "R110DC",
    "descr": "KELS - HEALTH CARE",
    "cbmLoc": 202,
    "stock": 97,
    "utilization": 48.2
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DD",
    "putawayzone": "R110DD",
    "descr": "KELS - BEAUTY CARE",
    "cbmLoc": 232,
    "stock": 1,
    "utilization": 0.4
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 58,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EF",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 800,
    "utilization": 0
  },
  {
    "periode": "1 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EG",
    "putawayzone": "R110EG",
    "descr": "SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 885,
    "stock": 19,
    "utilization": 2.2
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100A",
    "putawayzone": "R1100A",
    "descr": "LIVING UPHOLSTERED",
    "cbmLoc": 5886,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100I",
    "putawayzone": "R1100I",
    "descr": "LIGHTING",
    "cbmLoc": 170,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100J",
    "putawayzone": "R1100J",
    "descr": "MATTRESS",
    "cbmLoc": 24,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100M",
    "putawayzone": "R1100M",
    "descr": "HOME TEXTILE",
    "cbmLoc": 643,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100N",
    "putawayzone": "R1100N",
    "descr": "HOME DECORE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100O",
    "putawayzone": "R1100O",
    "descr": "HOMEWARE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100X",
    "putawayzone": "R1100X",
    "descr": "NON MERCHANDISE",
    "cbmLoc": 3,
    "stock": 3,
    "utilization": 83.5
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AB",
    "putawayzone": "R110AB",
    "descr": "HOME CLASSIC",
    "cbmLoc": 4884,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AE",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AF",
    "putawayzone": "R110AF",
    "descr": "BROWN GOODS",
    "cbmLoc": 111,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AG",
    "putawayzone": "R110AG",
    "descr": "WHITE GOODS",
    "cbmLoc": 455,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AM",
    "putawayzone": "R110AM",
    "descr": "CUSTOME FURNITURE",
    "cbmLoc": 2,
    "stock": 1,
    "utilization": 47.5
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AQ",
    "putawayzone": "R110AQ",
    "descr": "SELMA",
    "cbmLoc": 126,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 6975,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BB",
    "putawayzone": "R110BB",
    "descr": "TABLE & CABINET",
    "cbmLoc": 10059,
    "stock": 1132,
    "utilization": 11.3
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BC",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 4956,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BD",
    "putawayzone": "R110BD",
    "descr": "DINING",
    "cbmLoc": 2737,
    "stock": 1828,
    "utilization": 66.8
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BE",
    "putawayzone": "R110BE",
    "descr": "KITCHEN",
    "cbmLoc": 247,
    "stock": 240,
    "utilization": 97.5
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BF",
    "putawayzone": "R110BF",
    "descr": "BEDROOM",
    "cbmLoc": 2775,
    "stock": 1835,
    "utilization": 66.1
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BG",
    "putawayzone": "R110BG",
    "descr": "MATTRESS",
    "cbmLoc": 9138,
    "stock": 5739,
    "utilization": 62.8
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BH",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 119,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BI",
    "putawayzone": "R110BI",
    "descr": "KIDS SPACE",
    "cbmLoc": 996,
    "stock": 637,
    "utilization": 64
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BJ",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 364,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BK",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 975,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BL",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 63,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BM",
    "putawayzone": "R110BM",
    "descr": "HOME ORGANIZER",
    "cbmLoc": 541,
    "stock": 489,
    "utilization": 90.5
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BN",
    "putawayzone": "R110BN",
    "descr": "HOMEWARE",
    "cbmLoc": 364,
    "stock": 124,
    "utilization": 34.1
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BO",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 10,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BP",
    "putawayzone": "R110BP",
    "descr": "OFFICE",
    "cbmLoc": 2839,
    "stock": 1468,
    "utilization": 51.7
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BQ",
    "putawayzone": "R110BQ",
    "descr": "OFFICE SEATING",
    "cbmLoc": 4276,
    "stock": 4818,
    "utilization": 112.7
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BR",
    "putawayzone": "R110BR",
    "descr": "COMMERCIAL & BUSINESS",
    "cbmLoc": 6248,
    "stock": 4066,
    "utilization": 65.1
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 394,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CB",
    "putawayzone": "R110CB",
    "descr": "TEXTILE",
    "cbmLoc": 428,
    "stock": 3,
    "utilization": 0.6
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CC",
    "putawayzone": "R110CC",
    "descr": "KASUR",
    "cbmLoc": 955,
    "stock": 260,
    "utilization": 27.2
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CD",
    "putawayzone": "R110CD",
    "descr": "RUANG TAMU & PENYIMPANAN",
    "cbmLoc": 449,
    "stock": 144,
    "utilization": 32.1
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CE",
    "putawayzone": "R110CE",
    "descr": "RUANG MAKAN & DAPUR",
    "cbmLoc": 731,
    "stock": 96,
    "utilization": 13.2
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CF",
    "putawayzone": "R110CF",
    "descr": "PERALATAN MAKAN & DAPUR",
    "cbmLoc": 126,
    "stock": 15,
    "utilization": 11.6
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CG",
    "putawayzone": "R110CG",
    "descr": "RUANG TIDUR",
    "cbmLoc": 428,
    "stock": 107,
    "utilization": 24.9
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CH",
    "putawayzone": "R110CH",
    "descr": "PERLENGKAPAN RUMAH",
    "cbmLoc": 428,
    "stock": 19,
    "utilization": 4.4
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CI",
    "putawayzone": "R110CI",
    "descr": "RUANG KERJA & BELAJAR",
    "cbmLoc": 1645,
    "stock": 131,
    "utilization": 8
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DA",
    "putawayzone": "R110DA",
    "descr": "KELS - MAJOR DOMESTIC APPLIANCES",
    "cbmLoc": 209,
    "stock": 27,
    "utilization": 12.9
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DB",
    "putawayzone": "R110DB",
    "descr": "KELS - SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 212,
    "stock": 30,
    "utilization": 14.2
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DC",
    "putawayzone": "R110DC",
    "descr": "KELS - HEALTH CARE",
    "cbmLoc": 202,
    "stock": 105,
    "utilization": 52.1
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DD",
    "putawayzone": "R110DD",
    "descr": "KELS - BEAUTY CARE",
    "cbmLoc": 232,
    "stock": 1,
    "utilization": 0.4
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 60,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EF",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 789,
    "utilization": 0
  },
  {
    "periode": "2 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EG",
    "putawayzone": "R110EG",
    "descr": "SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 885,
    "stock": 17,
    "utilization": 2
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100A",
    "putawayzone": "R1100A",
    "descr": "LIVING UPHOLSTERED",
    "cbmLoc": 5886,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100I",
    "putawayzone": "R1100I",
    "descr": "LIGHTING",
    "cbmLoc": 170,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100J",
    "putawayzone": "R1100J",
    "descr": "MATTRESS",
    "cbmLoc": 24,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100M",
    "putawayzone": "R1100M",
    "descr": "HOME TEXTILE",
    "cbmLoc": 643,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100N",
    "putawayzone": "R1100N",
    "descr": "HOME DECORE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100O",
    "putawayzone": "R1100O",
    "descr": "HOMEWARE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100X",
    "putawayzone": "R1100X",
    "descr": "NON MERCHANDISE",
    "cbmLoc": 3,
    "stock": 3,
    "utilization": 83.5
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AB",
    "putawayzone": "R110AB",
    "descr": "HOME CLASSIC",
    "cbmLoc": 4884,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AE",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AF",
    "putawayzone": "R110AF",
    "descr": "BROWN GOODS",
    "cbmLoc": 111,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AG",
    "putawayzone": "R110AG",
    "descr": "WHITE GOODS",
    "cbmLoc": 455,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AM",
    "putawayzone": "R110AM",
    "descr": "CUSTOME FURNITURE",
    "cbmLoc": 2,
    "stock": 1,
    "utilization": 47.5
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AQ",
    "putawayzone": "R110AQ",
    "descr": "SELMA",
    "cbmLoc": 126,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 6865,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BB",
    "putawayzone": "R110BB",
    "descr": "TABLE & CABINET",
    "cbmLoc": 10059,
    "stock": 1134,
    "utilization": 11.3
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BC",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 4873,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BD",
    "putawayzone": "R110BD",
    "descr": "DINING",
    "cbmLoc": 2737,
    "stock": 1794,
    "utilization": 65.5
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BE",
    "putawayzone": "R110BE",
    "descr": "KITCHEN",
    "cbmLoc": 247,
    "stock": 236,
    "utilization": 95.8
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BF",
    "putawayzone": "R110BF",
    "descr": "BEDROOM",
    "cbmLoc": 2775,
    "stock": 1810,
    "utilization": 65.2
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BG",
    "putawayzone": "R110BG",
    "descr": "MATTRESS",
    "cbmLoc": 9138,
    "stock": 5679,
    "utilization": 62.1
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BH",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 117,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BI",
    "putawayzone": "R110BI",
    "descr": "KIDS SPACE",
    "cbmLoc": 996,
    "stock": 625,
    "utilization": 62.7
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BJ",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 356,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BK",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 973,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BL",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 61,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BM",
    "putawayzone": "R110BM",
    "descr": "HOME ORGANIZER",
    "cbmLoc": 541,
    "stock": 483,
    "utilization": 89.4
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BN",
    "putawayzone": "R110BN",
    "descr": "HOMEWARE",
    "cbmLoc": 364,
    "stock": 122,
    "utilization": 33.6
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BO",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 9,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BP",
    "putawayzone": "R110BP",
    "descr": "OFFICE",
    "cbmLoc": 2839,
    "stock": 1468,
    "utilization": 51.7
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BQ",
    "putawayzone": "R110BQ",
    "descr": "OFFICE SEATING",
    "cbmLoc": 4276,
    "stock": 4779,
    "utilization": 111.8
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BR",
    "putawayzone": "R110BR",
    "descr": "COMMERCIAL & BUSINESS",
    "cbmLoc": 6248,
    "stock": 4003,
    "utilization": 64.1
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 523,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CB",
    "putawayzone": "R110CB",
    "descr": "TEXTILE",
    "cbmLoc": 428,
    "stock": 8,
    "utilization": 1.9
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CC",
    "putawayzone": "R110CC",
    "descr": "KASUR",
    "cbmLoc": 955,
    "stock": 249,
    "utilization": 26.1
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CD",
    "putawayzone": "R110CD",
    "descr": "RUANG TAMU & PENYIMPANAN",
    "cbmLoc": 449,
    "stock": 171,
    "utilization": 37.9
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CE",
    "putawayzone": "R110CE",
    "descr": "RUANG MAKAN & DAPUR",
    "cbmLoc": 731,
    "stock": 97,
    "utilization": 13.2
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CF",
    "putawayzone": "R110CF",
    "descr": "PERALATAN MAKAN & DAPUR",
    "cbmLoc": 126,
    "stock": 15,
    "utilization": 11.6
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CG",
    "putawayzone": "R110CG",
    "descr": "RUANG TIDUR",
    "cbmLoc": 428,
    "stock": 104,
    "utilization": 24.2
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CH",
    "putawayzone": "R110CH",
    "descr": "PERLENGKAPAN RUMAH",
    "cbmLoc": 428,
    "stock": 26,
    "utilization": 6.1
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CI",
    "putawayzone": "R110CI",
    "descr": "RUANG KERJA & BELAJAR",
    "cbmLoc": 1645,
    "stock": 133,
    "utilization": 8.1
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DA",
    "putawayzone": "R110DA",
    "descr": "KELS - MAJOR DOMESTIC APPLIANCES",
    "cbmLoc": 209,
    "stock": 22,
    "utilization": 10.6
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DB",
    "putawayzone": "R110DB",
    "descr": "KELS - SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 212,
    "stock": 28,
    "utilization": 13.3
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DC",
    "putawayzone": "R110DC",
    "descr": "KELS - HEALTH CARE",
    "cbmLoc": 202,
    "stock": 102,
    "utilization": 50.5
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DD",
    "putawayzone": "R110DD",
    "descr": "KELS - BEAUTY CARE",
    "cbmLoc": 232,
    "stock": 1,
    "utilization": 0.4
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 53,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EF",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 779,
    "utilization": 0
  },
  {
    "periode": "3 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EG",
    "putawayzone": "R110EG",
    "descr": "SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 885,
    "stock": 17,
    "utilization": 1.9
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100A",
    "putawayzone": "R1100A",
    "descr": "LIVING UPHOLSTERED",
    "cbmLoc": 5886,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100I",
    "putawayzone": "R1100I",
    "descr": "LIGHTING",
    "cbmLoc": 170,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100J",
    "putawayzone": "R1100J",
    "descr": "MATTRESS",
    "cbmLoc": 24,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100M",
    "putawayzone": "R1100M",
    "descr": "HOME TEXTILE",
    "cbmLoc": 643,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100N",
    "putawayzone": "R1100N",
    "descr": "HOME DECORE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100O",
    "putawayzone": "R1100O",
    "descr": "HOMEWARE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100X",
    "putawayzone": "R1100X",
    "descr": "NON MERCHANDISE",
    "cbmLoc": 3,
    "stock": 3,
    "utilization": 85
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AB",
    "putawayzone": "R110AB",
    "descr": "HOME CLASSIC",
    "cbmLoc": 4884,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AE",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AF",
    "putawayzone": "R110AF",
    "descr": "BROWN GOODS",
    "cbmLoc": 111,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AG",
    "putawayzone": "R110AG",
    "descr": "WHITE GOODS",
    "cbmLoc": 455,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AM",
    "putawayzone": "R110AM",
    "descr": "CUSTOME FURNITURE",
    "cbmLoc": 2,
    "stock": 1,
    "utilization": 47.5
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AQ",
    "putawayzone": "R110AQ",
    "descr": "SELMA",
    "cbmLoc": 126,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 6860,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BB",
    "putawayzone": "R110BB",
    "descr": "TABLE & CABINET",
    "cbmLoc": 10059,
    "stock": 1168,
    "utilization": 11.6
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BC",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 4850,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BD",
    "putawayzone": "R110BD",
    "descr": "DINING",
    "cbmLoc": 2737,
    "stock": 1778,
    "utilization": 65
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BE",
    "putawayzone": "R110BE",
    "descr": "KITCHEN",
    "cbmLoc": 247,
    "stock": 234,
    "utilization": 94.7
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BF",
    "putawayzone": "R110BF",
    "descr": "BEDROOM",
    "cbmLoc": 2775,
    "stock": 1787,
    "utilization": 64.4
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BG",
    "putawayzone": "R110BG",
    "descr": "MATTRESS",
    "cbmLoc": 9138,
    "stock": 5748,
    "utilization": 62.9
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BH",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 116,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BI",
    "putawayzone": "R110BI",
    "descr": "KIDS SPACE",
    "cbmLoc": 996,
    "stock": 617,
    "utilization": 61.9
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BJ",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 353,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BK",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 980,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BL",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 65,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BM",
    "putawayzone": "R110BM",
    "descr": "HOME ORGANIZER",
    "cbmLoc": 541,
    "stock": 485,
    "utilization": 89.7
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BN",
    "putawayzone": "R110BN",
    "descr": "HOMEWARE",
    "cbmLoc": 364,
    "stock": 123,
    "utilization": 33.8
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BO",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 9,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BP",
    "putawayzone": "R110BP",
    "descr": "OFFICE",
    "cbmLoc": 2839,
    "stock": 1482,
    "utilization": 52.2
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BQ",
    "putawayzone": "R110BQ",
    "descr": "OFFICE SEATING",
    "cbmLoc": 4276,
    "stock": 5009,
    "utilization": 117.2
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BR",
    "putawayzone": "R110BR",
    "descr": "COMMERCIAL & BUSINESS",
    "cbmLoc": 6248,
    "stock": 4170,
    "utilization": 66.7
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 532,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CB",
    "putawayzone": "R110CB",
    "descr": "TEXTILE",
    "cbmLoc": 428,
    "stock": 9,
    "utilization": 2
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CC",
    "putawayzone": "R110CC",
    "descr": "KASUR",
    "cbmLoc": 955,
    "stock": 296,
    "utilization": 31
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CD",
    "putawayzone": "R110CD",
    "descr": "RUANG TAMU & PENYIMPANAN",
    "cbmLoc": 449,
    "stock": 166,
    "utilization": 37
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CE",
    "putawayzone": "R110CE",
    "descr": "RUANG MAKAN & DAPUR",
    "cbmLoc": 731,
    "stock": 93,
    "utilization": 12.7
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CF",
    "putawayzone": "R110CF",
    "descr": "PERALATAN MAKAN & DAPUR",
    "cbmLoc": 126,
    "stock": 15,
    "utilization": 12.1
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CG",
    "putawayzone": "R110CG",
    "descr": "RUANG TIDUR",
    "cbmLoc": 428,
    "stock": 111,
    "utilization": 26
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CH",
    "putawayzone": "R110CH",
    "descr": "PERLENGKAPAN RUMAH",
    "cbmLoc": 428,
    "stock": 26,
    "utilization": 6.1
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CI",
    "putawayzone": "R110CI",
    "descr": "RUANG KERJA & BELAJAR",
    "cbmLoc": 1645,
    "stock": 156,
    "utilization": 9.5
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DA",
    "putawayzone": "R110DA",
    "descr": "KELS - MAJOR DOMESTIC APPLIANCES",
    "cbmLoc": 209,
    "stock": 23,
    "utilization": 11.1
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DB",
    "putawayzone": "R110DB",
    "descr": "KELS - SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 212,
    "stock": 29,
    "utilization": 13.5
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DC",
    "putawayzone": "R110DC",
    "descr": "KELS - HEALTH CARE",
    "cbmLoc": 202,
    "stock": 102,
    "utilization": 50.4
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DD",
    "putawayzone": "R110DD",
    "descr": "KELS - BEAUTY CARE",
    "cbmLoc": 232,
    "stock": 1,
    "utilization": 0.4
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 52,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EF",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 770,
    "utilization": 0
  },
  {
    "periode": "4 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EG",
    "putawayzone": "R110EG",
    "descr": "SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 885,
    "stock": 16,
    "utilization": 1.8
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100A",
    "putawayzone": "R1100A",
    "descr": "LIVING UPHOLSTERED",
    "cbmLoc": 5886,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100I",
    "putawayzone": "R1100I",
    "descr": "LIGHTING",
    "cbmLoc": 170,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100J",
    "putawayzone": "R1100J",
    "descr": "MATTRESS",
    "cbmLoc": 24,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100M",
    "putawayzone": "R1100M",
    "descr": "HOME TEXTILE",
    "cbmLoc": 643,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100N",
    "putawayzone": "R1100N",
    "descr": "HOME DECORE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100O",
    "putawayzone": "R1100O",
    "descr": "HOMEWARE",
    "cbmLoc": 1,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R1100X",
    "putawayzone": "R1100X",
    "descr": "NON MERCHANDISE",
    "cbmLoc": 3,
    "stock": 4,
    "utilization": 137.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AB",
    "putawayzone": "R110AB",
    "descr": "HOME CLASSIC",
    "cbmLoc": 4884,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AE",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AF",
    "putawayzone": "R110AF",
    "descr": "BROWN GOODS",
    "cbmLoc": 111,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AG",
    "putawayzone": "R110AG",
    "descr": "WHITE GOODS",
    "cbmLoc": 455,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AM",
    "putawayzone": "R110AM",
    "descr": "CUSTOME FURNITURE",
    "cbmLoc": 2,
    "stock": 1,
    "utilization": 47.5
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110AQ",
    "putawayzone": "R110AQ",
    "descr": "SELMA",
    "cbmLoc": 126,
    "stock": 0,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 6818,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BB",
    "putawayzone": "R110BB",
    "descr": "TABLE & CABINET",
    "cbmLoc": 10059,
    "stock": 1185,
    "utilization": 11.8
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BC",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 5064,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BD",
    "putawayzone": "R110BD",
    "descr": "DINING",
    "cbmLoc": 2737,
    "stock": 1766,
    "utilization": 64.5
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BE",
    "putawayzone": "R110BE",
    "descr": "KITCHEN",
    "cbmLoc": 247,
    "stock": 231,
    "utilization": 93.7
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BF",
    "putawayzone": "R110BF",
    "descr": "BEDROOM",
    "cbmLoc": 2775,
    "stock": 1823,
    "utilization": 65.7
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BG",
    "putawayzone": "R110BG",
    "descr": "MATTRESS",
    "cbmLoc": 9138,
    "stock": 5734,
    "utilization": 62.8
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BH",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 116,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BI",
    "putawayzone": "R110BI",
    "descr": "KIDS SPACE",
    "cbmLoc": 996,
    "stock": 612,
    "utilization": 61.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BJ",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 364,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BK",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 978,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BL",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 65,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BM",
    "putawayzone": "R110BM",
    "descr": "HOME ORGANIZER",
    "cbmLoc": 541,
    "stock": 485,
    "utilization": 89.8
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BN",
    "putawayzone": "R110BN",
    "descr": "HOMEWARE",
    "cbmLoc": 364,
    "stock": 126,
    "utilization": 34.6
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BO",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 9,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BP",
    "putawayzone": "R110BP",
    "descr": "OFFICE",
    "cbmLoc": 2839,
    "stock": 1476,
    "utilization": 52
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BQ",
    "putawayzone": "R110BQ",
    "descr": "OFFICE SEATING",
    "cbmLoc": 4276,
    "stock": 5046,
    "utilization": 118
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110BR",
    "putawayzone": "R110BR",
    "descr": "COMMERCIAL & BUSINESS",
    "cbmLoc": 6248,
    "stock": 4138,
    "utilization": 66.2
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 522,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CB",
    "putawayzone": "R110CB",
    "descr": "TEXTILE",
    "cbmLoc": 428,
    "stock": 8,
    "utilization": 1.9
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CC",
    "putawayzone": "R110CC",
    "descr": "KASUR",
    "cbmLoc": 955,
    "stock": 290,
    "utilization": 30.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CD",
    "putawayzone": "R110CD",
    "descr": "RUANG TAMU & PENYIMPANAN",
    "cbmLoc": 449,
    "stock": 164,
    "utilization": 36.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CE",
    "putawayzone": "R110CE",
    "descr": "RUANG MAKAN & DAPUR",
    "cbmLoc": 731,
    "stock": 111,
    "utilization": 15.2
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CF",
    "putawayzone": "R110CF",
    "descr": "PERALATAN MAKAN & DAPUR",
    "cbmLoc": 126,
    "stock": 17,
    "utilization": 13.3
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CG",
    "putawayzone": "R110CG",
    "descr": "RUANG TIDUR",
    "cbmLoc": 428,
    "stock": 124,
    "utilization": 29
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CH",
    "putawayzone": "R110CH",
    "descr": "PERLENGKAPAN RUMAH",
    "cbmLoc": 428,
    "stock": 26,
    "utilization": 6
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110CI",
    "putawayzone": "R110CI",
    "descr": "RUANG KERJA & BELAJAR",
    "cbmLoc": 1645,
    "stock": 154,
    "utilization": 9.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DA",
    "putawayzone": "R110DA",
    "descr": "KELS - MAJOR DOMESTIC APPLIANCES",
    "cbmLoc": 209,
    "stock": 23,
    "utilization": 10.8
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DB",
    "putawayzone": "R110DB",
    "descr": "KELS - SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 212,
    "stock": 30,
    "utilization": 14.3
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DC",
    "putawayzone": "R110DC",
    "descr": "KELS - HEALTH CARE",
    "cbmLoc": 202,
    "stock": 102,
    "utilization": 50.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110DD",
    "putawayzone": "R110DD",
    "descr": "KELS - BEAUTY CARE",
    "cbmLoc": 232,
    "stock": 1,
    "utilization": 0.4
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EA",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 54,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EF",
    "putawayzone": "",
    "descr": "",
    "cbmLoc": 0,
    "stock": 764,
    "utilization": 0
  },
  {
    "periode": "5 Jun 2026",
    "whseid": "WMWHSE10",
    "storerkey": "HCI",
    "skuGroup": "R110EG",
    "putawayzone": "R110EG",
    "descr": "SMALL DOMESTIC APPLIANCES",
    "cbmLoc": 885,
    "stock": 16,
    "utilization": 1.8
  }
];